[platformio]
src_dir = src

[env:dueUSB]
platform = atmelsam
board = dueUSB
framework = arduino
monitor_speed = 115200

; Upload and monitor through the Native USB connector. Its COM port can differ
; from the Programming USB connector, so let PlatformIO auto-detect it.

lib_deps =
  https://github.com/collin80/can_common.git
  https://github.com/collin80/due_can.git
  arduino-libraries/SD

