[platformio]
src_dir = src

[env:due]
platform = atmelsam
board = due
framework = arduino
monitor_speed = 115200

; Set these once the Due is connected. They are intentionally left as COM5
; because the current workspace has been using COM5 for flashing.
upload_port = COM5
monitor_port = COM5

lib_deps =
  https://github.com/collin80/can_common.git
  https://github.com/collin80/due_can.git

